#!/bin/bash

set_common_vars() {

version="desy_dev"

categories_mutau="cat_mutau_sr"
variables_mutau='mutau_lep0_pt,mutau_lep0_eta,mutau_lep0_phi,mutau_lep0_ip_sig,mutau_lep1_pt,mutau_lep1_eta,mutau_lep1_phi,mutau_lep1_mass,mutau_lep1_decayModePNet,mutau_lep1_decayMode,mutau_mt,mutau_mvis,mutau_delta_eta,mutau_delta_r,mutau_pt,puppi_met_pt,puppi_met_phi'

categories_etau="cat_etau_sr"
# cat_etau_sr_no_mT,cat_etau_sr_b_jets,cat_etau_sr_b_jets_no_mT,cat_etau_sr_0_bjets,cat_etau_sr_0_bjets_endcap_tau,cat_etau_sr_0_bjets_barrel_tau,cat_etau_sr_0_bjets_no_mt,cat_etau_sr_0_bjets_endcap_tau_no_mt,cat_etau_sr_0_bjets_barrel_tau_no_mt,cat_etau_sr_1_bjets,cat_etau_sr_1_bjets_endcap_tau,cat_etau_sr_1_bjets_barrel_tau,cat_etau_sr_1_bjets_no_mt,cat_etau_sr_1_bjets_endcap_tau_no_mt,cat_etau_sr_1_bjets_barrel_tau_no_mt,cat_etau_sr_2_bjets,cat_etau_sr_2_bjets_endcap_tau,cat_etau_sr_2_bjets_barrel_tau,cat_etau_sr_2_bjets_no_mt,cat_etau_sr_2_bjets_endcap_tau_no_mt,cat_etau_sr_2_bjets_barrel_tau_no_mt"
variables_etau='mjj,N_b_jets,N_jets_pT_20_eta_2_5_Tight,mjj,N_jets_pT_20_eta_4_7_Tight,Leading_jet_pt,Subleading_jet_pt,delta_eta_jj,etau_lep0_pt,etau_lep0_eta,etau_lep0_phi,etau_lep0_ip_sig,etau_lep1_pt,etau_lep1_eta,etau_lep1_phi,etau_lep1_mass,etau_lep1_decayModePNet,etau_lep1_decayMode,etau_mt,etau_mvis,etau_delta_r,etau_pt,puppi_met_pt,puppi_met_phi'

categories_emu="cat_emu_sr,cat_emu_sr__nj0__dzl,cat_emu_sr__nj0__dzm,cat_emu_sr__nj1__dzl,cat_emu_sr__nj1__dzm" #,cat_emu_sr__nj2__dzl,cat_emu_sr__nj2__dzm,cat_emu_sr__nj2__dzh"
categories_emu_lim="cat_emu_sr__nj0__dzl"
#,cat_emu_sr_no_mT,cat_emu_sr_b_jets,cat_emu_sr_b_jets_no_mT,cat_emu_sr_0_bjets,cat_emu_sr_0_bjets_endcap_tau,cat_emu_sr_0_bjets_barrel_tau,cat_emu_sr_0_bjets_no_mt,cat_emu_sr_0_bjets_endcap_tau_no_mt,cat_emu_sr_0_bjets_barrel_tau_no_mt,cat_emu_sr_1_bjets,cat_emu_sr_1_bjets_endcap_tau,cat_emu_sr_1_bjets_barrel_tau,cat_emu_sr_1_bjets_no_mt,cat_emu_sr_1_bjets_endcap_tau_no_mt,cat_emu_sr_1_bjets_barrel_tau_no_mt,cat_emu_sr_2_bjets,cat_emu_sr_2_bjets_endcap_tau,cat_emu_sr_2_bjets_barrel_tau,cat_emu_sr_2_bjets_no_mt,cat_emu_sr_2_bjets_endcap_tau_no_mt,cat_emu_sr_2_bjets_barrel_tau_no_mt"
categories_emu_qcd="cat_emu_ar_qcd,cat_emu_dr_num_qcd,cat_emu_dr_den_qcd"
variables_emu='emu_mt_tot_fit,emu_mt_tot,emu_mt_emu,D_zeta,emu_mt_e,emu_mt_mu,N_jets_pT_20_eta_4_7_Tight,leading_jet_eta,subleading_jet_eta,leading_jet_phi,subleading_jet_phi,N_b_jets,N_jets_pT_20_eta_4_7_Tight,leading_jet_pt,subleading_jet_pt,delta_eta_jj,emu_lep0_pt,emu_lep0_eta,emu_lep0_phi,emu_lep0_ip_sig,emu_lep1_pt,emu_lep1_eta,emu_lep1_phi,emu_lep1_ip_sig,emu_mvis,emu_delta_r,emu_pt,puppi_met_pt,puppi_met_phi'
#mjj
data_egamma_2022preEE='data_egamma_C,data_egamma_D,'
data_muoneg_2022preEE='data_muoneg_C,data_muoneg_D,'
data_mu_2022preEE='data_mu_C,data_mu_D,data_singlemu_C,'

data_egamma_2022postEE='data_egamma_E,data_egamma_F,data_egamma_G,'
data_muoneg_2022postEE='data_muoneg_E,data_muoneg_F,data_muoneg_G,'
data_mu_2022postEE='data_mu_E,data_mu_F,data_mu_G,'

bkg_ewk='wj_incl_madgraph,ww,wz,zz,dy_lep_madgraph,'
bkg_top='st_twchannel_t_dl,st_twchannel_t_sl,st_twchannel_tbar_sl,st_twchannel_tbar_dl,st_tchannel_tbar,st_tchannel_t,st_schannel_t_lep,st_schannel_tbar_lep,'
bkg_ttbar='tt_sl,tt_dl,tt_fh,'
mssm_signal='h_ggf_htt_60,h_ggf_htt_65,h_ggf_htt_70,h_ggf_htt_75,h_ggf_htt_80,h_ggf_htt_85,h_ggf_htt_90,h_ggf_htt_95,h_ggf_htt_100,h_ggf_htt_105,h_ggf_htt_110,h_ggf_htt_115,h_ggf_htt_120,h_ggf_htt_125,h_ggf_htt_130,h_ggf_htt_135,h_ggf_htt_140,h_ggf_htt_160,h_ggf_htt_180,h_ggf_htt_200,h_ggf_htt_250,h_ggf_htt_300,h_ggf_htt_350,h_ggf_htt_400,h_ggf_htt_450,h_ggf_htt_500,h_ggf_htt_600,h_ggf_htt_700,h_ggf_htt_800,h_ggf_htt_900,h_ggf_htt_1000,h_ggf_htt_1100,h_ggf_htt_1200,h_ggf_htt_1400,h_ggf_htt_1600,h_ggf_htt_1800,h_ggf_htt_2000,h_ggf_htt_2300,h_ggf_htt_2600,h_ggf_htt_2900,h_ggf_htt_3200,h_ggf_htt_3500'
mssm_signal_80_100_120='h_ggf_htt_80,h_ggf_htt_100,h_ggf_htt_120,'
mssm_signal_100='h_ggf_htt_100,'
h_ggf_htt_80='h_ggf_htt_80,'
#st_twchannel_t_dl
data_egamma_2023preBPix='data_egamma_Cv123,data_egamma_Cv4,'
data_egamma_2023postBPix='data_egamma_D,'
data_muoneg_2023preBPix='data_muoneg_Cv123,data_muoneg_Cv4,'
data_muoneg_2023postBPix='data_muoneg_D,'
data_mu_2023preBPix='data_mu_Cv4,data_mu_Cv123,'
data_mu_2023postBPix='data_mu_D,'

case $1 in
################################
####### 2022preEE_limited ######
################################
    "run3_2022preEE_etau_lim")
        config="run3_2022_preEE_etau_limited"	
        datasets='data_egamma_C,dy_lep_madgraph'
        processes='data,dy_z2tautau,dy_z2mumu,dy_z2ee'
	      categories='cat_etau_sr'
	      variables='N_b_jets'
        workflow='local'
    ;;
    "run3_2022preEE_emu_lim")
        config="run3_2022_preEE_emu_limited"	
        datasets='dy_lep_madgraph,wj_incl_madgraph,data_egamma_C,' 
        processes='dy_lep,wj,data,' 
	    categories='cat_emu_sr__bdt_sig'
	    variables='pt_H,hcand_emu_fastMTT_mass,bdt_raw_score_sig,bdt_raw_score_dy,bdt_raw_score_tt,bdt_raw_score_wj'
        workflow='local'
    ;;
    "run3_2022preEE_mutau_lim")
        config="run3_2022_preEE_mutau_limited"	
        datasets='data_mu_C,dy_lep_madgraph'
        processes='dy_z2mumu,dy_z2ee,dy_z2tautau,data'
	      categories='cat_mutau_sr'
	      variables='N_b_jets'
        workflow='local'
    ;;
#########################
####### 2022preEE #######
#########################
    "run3_2022preEE_etau")
        config="run3_2022_preEE_etau"
        data=$data_egamma_2022preEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar
        processes='data,dy_z2tautau,dy_z2mumu,dy_z2ee,vv,tt,st,wj'
	      categories=$categories_etau
	      variables=$variables_etau
        workflow='htcondor'
    ;;
    "run3_2022preEE_emu")
        config="run3_2022_preEE_emu"
        data=$data_egamma_2022preEE$data_mu_2022preEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar$mssm_signal
        processes='dy_lep,vv,tt,st,wj,data,h_ggf_htt_masses'
	    categories=$categories_emu
	    variables=$variables_emu
	    workflow='htcondor'
    ;;
    "run3_2022preEE_emu_FF")
        config="run3_2022_preEE_emu"
        data=$data_egamma_2022preEE$data_mu_2022preEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar
        processes='dy_lep,vv,tt,st,wj,data'
	    categories=$categories_emu
	    variables=$variables_emu
	    workflow='htcondor'
    ;;
    "run3_2022preEE_emu_sig")
        config="run3_2022_preEE_emu"
        data=$data_egamma_2022preEE$data_mu_2022preEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$mssm_signal
        processes='h_ggf_htt_masses'
	    categories=$categories_emu
	    variables=$variables_emu
	    workflow='htcondor'
    ;;
    "run3_2022preEE_emu_st")
        config="run3_2022_preEE_emu"
        datasets='st_twchannel_t_dl'
        processes='st'
	      categories='cat_emu_sr'
	      variables='N_b_jets'
	      workflow='local'
    ;;
    "run3_2022preEE_mutau")
        config="run3_2022_preEE_mutau"
        data=$data_mu_2022preEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets="$data$bkg_ewk$bkg_top$bkg_ttbar"
        processes='dy_z2tautau,dy_z2mumu,dy_z2ee,vv,tt,st,wj,data'
	      categories=$categories_mutau
	      variables=$variables_mutau
        workflow='htcondor'
     ;;
################################
###### 2022postEE_limited ######
################################  
    "run3_2022postEE_etau_lim")
        config="run3_2022_postEE_etau_limited"	
        datasets='data_egamma_E,dy_lep_madgraph'
        processes='data,dy_z2tautau,dy_z2mumu,dy_z2ee'
	      categories='cat_etau_sr'
	      variables='N_b_jets'
        workflow='local'
    ;;
    "run3_2022postEE_emu_lim")
        config="run3_2022_postEE_emu_limited"
        datasets='data_egamma_E,dy_lep_madgraph,h_ggf_htt_100'
        processes='data,dy_lep,h_ggf_htt_100'
	    categories='cat_emu_sr'
	    variables='bdt_raw_score_sig,bdt_raw_score_dy,bdt_raw_score_tt,bdt_raw_score_wj'
        workflow='local'
    ;;
    "run3_2022postEE_mutau_lim")
        config="run3_2022_postEE_mutau_limited"	
        datasets='data_mu_E,dy_lep_madgraph'
        processes='dy_z2mumu,dy_z2ee,dy_z2tautau,data'
	      categories='cat_mutau_sr'
	      variables='N_b_jets'
        workflow='local'
    ;;
#########################
####### 2022postEE ######
#########################
    "run3_2022postEE_etau")
        config="run3_2022_postEE_etau"
        data=$data_egamma_2022postEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar
        processes='dy_z2tautau,dy_z2mumu,dy_z2ee,vv,tt,st,wj,data'
	      categories=$categories_etau
	      variables=$variables_etau
	      workflow='htcondor'
    ;;
    "run3_2022postEE_emu")
        config="run3_2022_postEE_emu"
        data=$data_egamma_2022postEE$data_mu_2022postEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar # $mssm_signal
        processes='dy_lep,vv,tt,st,wj,data' #,h_ggf_htt_masses'
	    categories=$categories_emu
	    variables=$variables_emu
	    workflow='htcondor'
    ;;
    "run3_2022postEE_emu_1200")
        config="run3_2022_postEE_emu"
        datasets='h_ggf_htt_1200'
        processes='h_ggf_htt_1200'
	    categories=$categories_emu
	    variables=$variables_emu
	    workflow='htcondor'
    ;;
    "run3_2022postEE_emu_qcd")
        config="run3_2022_postEE_emu"
        data=$data_egamma_2022postEE$data_mu_2022postEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar$mssm_signal_80_100_1200
        processes='dy_lep,vv,tt,st,wj,data,h_ggf_htt_80,h_ggf_htt_100,h_ggf_htt_1200'
        # h_ggf_htt_60,h_ggf_htt_65,h_ggf_htt_70,h_ggf_htt_75,h_ggf_htt_80,h_ggf_htt_85,h_ggf_htt_90,h_ggf_htt_95,h_ggf_htt_100,h_ggf_htt_105,h_ggf_htt_110,h_ggf_htt_115,h_ggf_htt_120,h_ggf_htt_125,h_ggf_htt_130,h_ggf_htt_135,h_ggf_htt_140,h_ggf_htt_160,h_ggf_htt_180,h_ggf_htt_200,h_ggf_htt_250,h_ggf_htt_300,h_ggf_htt_350,h_ggf_htt_400,h_ggf_htt_450,h_ggf_htt_500,h_ggf_htt_600,h_ggf_htt_700,h_ggf_htt_800,h_ggf_htt_900,h_ggf_htt_1000,h_ggf_htt_1100,h_ggf_htt_1200,h_ggf_htt_1400,h_ggf_htt_1600,h_ggf_htt_1800,h_ggf_htt_2000,h_ggf_htt_2300,h_ggf_htt_2600,h_ggf_htt_2900,h_ggf_htt_3200,h_ggf_htt_3500'
	    categories=$categories_emu_qcd
	    variables=$variables_emu
	    workflow='htcondor'
    ;;
    "run3_2022postEE_emu_2D")
        config="run3_2022_postEE_emu"
        data=$data_egamma_2022postEE$data_mu_2022postEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$bkg_ewk$bkg_top$bkg_ttbar
        processes='dy_lep,vv,tt,st,wj'
	      categories=$categories_emu
	      variables='leading_jet_eta-leading_jet_phi'
	      workflow='htcondor'
    ;;
    "run3_2022postEE_emu_2D_dy")
        config="run3_2022_postEE_emu"
        datasets='dy_lep_madgraph'
        processes='dy_lep'
	      categories='cat_emu_sr'
	      variables='leading_jet_eta-leading_jet_phi'
	      workflow='local'
    ;;
    "run3_2022postEE_mutau")
        config="run3_2022_postEE_mutau"
        data=$data_mu_2022postEE
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
      	datasets="$data$bkg_ewk$bkg_top$bkg_ttbar"
        processes='dy_z2tautau,dy_z2mumu,dy_z2ee,vv,tt,st,wj,data'
	      categories=$categories_mutau
	      variables=$variables_mutau
	      workflow='htcondor'
    ;;
###################################
####### 2023preBPix_limited #######
###################################
    "run3_2023preBPix_etau_lim")
        config="run3_2023_preBPix_etau_limited"
        datasets='dy_lep_madgraph,data_egamma_Cv123'
        processes='dy_z2mumu,dy_z2ee,dy_z2tautau,data'
        categories='cat_etau_sr'
        variables='N_b_jets'
        workflow='local'
    ;;
    "run3_2023preBPix_emu_lim")
        config="run3_2023_preBPix_emu_limited"
        datasets='data_mu_Cv4,data_mu_Cv123' #dy_lep_madgraph
        processes='data' #dy_lep
        categories='cat_emu_sr'
        variables='emu_mt_tot_fit'
        workflow='local'
    ;;
    "run3_2023preBPix_mutau_lim")
        config="run3_2023_preBPix_mutau_limited"
        datasets='dy_lep_madgraph,data_mu_Cv123'
        processes='dy_z2mumu,dy_z2ee,dy_z2tautau,data'
        categories='cat_mutau_sr'
        variables='N_b_jets'
        workflow='local'
    ;;
##############################
####### 2023preBPix ##########
##############################
    "run3_2023preBPix_etau")
        config="run3_2023_preBPix_etau"
        data=$data_egamma_2023preBPix
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets="$data$bkg_ewk$bkg_top$bkg_ttbar"
        processes='dy_z2tautau,dy_z2mumu,dy_z2ee,vv,tt,st,wj,data'
        categories=$categories_etau
        variables=$variables_etau
        workflow='htcondor'
    ;;
    "run3_2022preBPix_emu_FF")
        config="run3_2023_preBPix_emu"
        data=$data_egamma_2023preBPix$data_mu_2023preBPix
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar #$mssm_signal
        processes='dy_lep,vv,tt,st,wj,data' #,h_ggf_htt_masses'
        # h_ggf_htt_60,h_ggf_htt_65,h_ggf_htt_70,h_ggf_htt_75,h_ggf_htt_80,h_ggf_htt_85,h_ggf_htt_90,h_ggf_htt_95,h_ggf_htt_100,h_ggf_htt_105,h_ggf_htt_110,h_ggf_htt_115,h_ggf_htt_120,h_ggf_htt_125,h_ggf_htt_130,h_ggf_htt_135,h_ggf_htt_140,h_ggf_htt_160,h_ggf_htt_180,h_ggf_htt_200,h_ggf_htt_250,h_ggf_htt_300,h_ggf_htt_350,h_ggf_htt_400,h_ggf_htt_450,h_ggf_htt_500,h_ggf_htt_600,h_ggf_htt_700,h_ggf_htt_800,h_ggf_htt_900,h_ggf_htt_1000,h_ggf_htt_1100,h_ggf_htt_1200,h_ggf_htt_1400,h_ggf_htt_1600,h_ggf_htt_1800,h_ggf_htt_2000,h_ggf_htt_2300,h_ggf_htt_2600,h_ggf_htt_2900,h_ggf_htt_3200,h_ggf_htt_3500'
	    categories=$categories_emu
	    variables=$variables_emu
	    workflow='htcondor'
    ;;
    "run3_2023preBPix_emu")
        config="run3_2023_preBPix_emu"
        data=$data_egamma_2023preBPix$data_mu_2023preBPix
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar$mssm_signal
        processes='dy_lep,vv,tt,st,wj,data,h_ggf_htt_masses'
        categories=$categories_emu
        variables=$variables_emu
        workflow='htcondor'
    ;;
    "run3_2023preBPix_mutau")
        config="run3_2023_preBPix_mutau"
        data=$data_mu_2023preBPix
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets="$data$bkg_ewk$bkg_top$bkg_ttbar"
        processes='dy_z2tautau,dy_z2mumu,dy_z2ee,vv,tt,st,wj,data'
        categories=$categories_mutau
        variables=$variables_mutau
        workflow='htcondor'
     ;;
####################################
####### 2023postBPix_limited #######
####################################
    "run3_2023postBPix_etau_lim")
        config="run3_2023_postBPix_etau_limited"
        datasets='dy_lep_madgraph,data_egamma_D'
        processes='dy_z2mumu,dy_z2ee,dy_z2tautau,data'
        categories='cat_etau_sr'
        variables='N_b_jets'
        workflow='local'
    ;;
    "run3_2023postBPix_emu_lim")
        config="run3_2023_postBPix_emu_limited"
        datasets='dy_lep_madgraph,data_muoneg_D'
        processes='dy_lep,data'
        categories='cat_emu_sr'
        variables='N_b_jets'
        workflow='local'
    ;;
    "run3_2023postBPix_mutau_lim")
        config="run3_2023_postBPix_mutau_limited"
        datasets='dy_lep_madgraph,data_mu_D'
        processes='dy_z2mumu,dy_z2ee,dy_z2tautau,data'
        categories='cat_mutau_sr'
        variables='N_b_jets'
        workflow='local'
    ;;
############################
####### 2023postBPix #######
############################
    "run3_2023postBPix_etau")
        config="run3_2023_postBPix_etau"
        data=$data_egamma_2023postBPix
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets="$data$bkg_ewk$bkg_top$bkg_ttbar"
        processes='dy_z2tautau,dy_z2mumu,dy_z2ee,vv,tt,st,wj,data'
        categories=$categories_etau
        variables=$variables_etau
        workflow='htcondor'
    ;;
    "run3_2023postBPix_emu")
        config="run3_2023_postBPix_emu"
        data=$data_egamma_2023postBPix$data_mu_2023postBPix
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar$mssm_signal
        processes='dy_lep,vv,tt,st,wj,data,h_ggf_htt_masses'
        categories=$categories_emu
        variables=$variables_emu
        workflow='htcondor'
    ;;
    "run3_2023postBPix_emu_FF")
        config="run3_2023_postBPix_emu"
        data=$data_egamma_2023postBPix$data_mu_2023postBPix
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets=$data$bkg_ewk$bkg_top$bkg_ttbar
        processes='dy_lep,vv,tt,st,wj,data'
        categories=$categories_emu
        variables=$variables_emu
        workflow='htcondor'
    ;;
    "run3_2023postBPix_mutau")
        config="run3_2023_postBPix_mutau"
        data=$data_mu_2023postBPix
        bkg_ewk=$bkg_ewk
        bkg_top=$bkg_top
        bkg_ttbar=$bkg_ttbar
        datasets="$data$bkg_ewk$bkg_top$bkg_ttbar"
        processes='dy_z2tautau,dy_z2mumu,dy_z2ee,vv,tt,st,wj,data'
        categories=$categories_mutau
        variables=$variables_mutau
        workflow='htcondor'
     ;;
    *)
    echo "Unknown run argument!"
    exit

esac
}
